### ISSUE TITLE
A small mistake in evaluation results

### ISSUE THREAD

**Issue by stunback** [Lynne-Zheng-Linfang/HS-Pose#1]
Hello, thanks for your nice work, but there is a mistake in the evaluation results in readme, where the IOU75 is larger than 50 and 25. Maybe it is a writing mistake.

**Comment by Lynne-Zheng-Linfang** [comment]
Thank you so much for pointing that out. Yes, the IoU75 and the IoU25 were flipped. I have updated the README.md file, and they should look right now.
