### ISSUE TITLE
fsnet_scale

### ISSUE THREAD

**Issue by saintrealchoi** [Lynne-Zheng-Linfang/HS-Pose#2]
First of All, Thank you for your AWESOME Works!
I have a question about PoseDataset.
I couldn't guess the meaning of `fsnet_scale`.
can you explain it?

**Comment by Lynne-Zheng-Linfang** [comment]
> First of All, Thank you for your AWESOME Work! I have a question about PoseDataset. I couldn't guess the meaning of `fsnet_scale`. can you explain it?

Thanks for your interest in this work. Sorry for the confusion. `fsnet_scale` is an object's residue size with respect to its corresponding category's mean size.  This was first introduced in the [FS-Net](https://github.com/DC1991/FS_Net) so we kept the name. I hope this helps.
