### ISSUE TITLE
why sample 1028 points in HS-Pose?

### ISSUE THREAD

**Issue by huiyang0613** [Lynne-Zheng-Linfang/HS-Pose#3]
Hi, Thank you so much for sharing the code. The previous method is to sample 1024 observation points, why sample 1028 points in HS-Pose? If it is changed to sampling 1024 points, will it affect network performance?

**Comment by Lynne-Zheng-Linfang** [comment]
Thanks for your interest in this work. We follow the [GPV-Pose](https://github.com/lolrudy/GPV_Pose/blob/master/config/config.py) to use 1028 points for the sampling and have not tested the influence of different point numbers. But using 1028 and 1024 points should output similar results.

**Comment by wusuoweima** [comment]
Why randomly sample 1028 points instead of uniform sampling?

**Comment by Lynne-Zheng-Linfang** [comment]
> Why randomly sample 1028 points instead of uniform sampling?

We use random permutation to ensure randomness during training and simply kept this during inference. However, using the furthest point sampling or uniform sampling may produce better results during inference, as they provide a better point distribution.
