### ISSUE TITLE
Question about torch Distributed 

### ISSUE THREAD

**Issue by wusuoweima** [Lynne-Zheng-Linfang/HS-Pose#4]
您好，方法性能很好，目前在学习您的代码，用单卡训练的话，训练时间较长， 使用多卡并行训练(torch.DistributedDataParallel) 可压缩训练时间，但是现有超参数(可能主要是学习率）不再适用，性能会变差

您有使用多卡并行训练(torch.DistributedDataParallel) 吗？ 效果如何？超参数 方便共享吗？
您的邮箱是 lxz948@student.bham.ac.uk ？

期待您的回复，谢谢
@Lynne-Zheng-Linfang

**Comment by Lynne-Zheng-Linfang** [comment]
您好，首先感谢您对HS-Pose的关注！我目前没有尝试过使用多卡并行训练HS-Pose，很抱歉没有办法提供相应的超参和具体效果。邮箱地址是正确的。

**Comment by wusuoweima** [comment]
非常感谢！
